### ISSUE TITLE
postbackのinputOptionに対応する

### ISSUE THREAD

**Issue by inoue2002** [e-chan1007/line-richmenu-editor#8]
- 2022/5/14付アップデートに対応
  - https://developers.line.biz/ja/news/2022/?month=05&day=13&article=richmenu-keyboard
  
![image](https://user-images.githubusercontent.com/54356188/168324243-1ee484a8-8273-44f9-8687-0acfb6eadd8e.png)

**Comment by e-chan1007** [comment]
- [x] #9
- [x] #10
